spring:
  datasource:
    master:
      url: jdbc:sqlserver://172.16.100.86:1433;databasename=SHDB_SH01
      username: reader
      password: SANhua?2019
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver

    cluster:
      url: jdbc:sqlserver://172.16.100.168:1433;databasename=SHDB_SH01
      username: sa
      password: 1234560_sh
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver

  thymeleaf:
    cache: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: sql-server
    open-in-view: false

server:
  port: 18080
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.entity

logging:
  level:
    com.example.demo.mapper: debug


